version: '3'
services:
  solr:
    image: solr
    ports:
      - "8983:8983"
    volumes:
      - data:/var/solr
    command:
      - solr-precreate
      - gettingstarted
volumes:
  data:

#    curl 'http://localhost:8983/solr/gettingstarted/update?commit=true' --data-binary @example/exampledocs/books.json -H 'Content-type:application/json'