version: "3.9"
services:
  app1:
    image: pr5spring
    ports:
      - 8080:8080
    restart: on-failure
    environment:
      - NAME_APP=app1

  app2:
    image: pr5spring
    restart: on-failure
    environment:
      - NAME_APP=app2

  app3:
    image: pr5spring
    restart: on-failure
    environment:
      - NAME_APP=app3

  app4:
    image: pr5spring
    restart: on-failure
    environment:
      - NAME_APP=app4
  proxy:
    image: nginx:1.11
    ports:
      - '80:80'
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
